import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "status-warning": "#F59E0B",
        "primary-fixed": "#dbe1ff",
        "surface-container-highest": "#d3e4fe",
        "surface-tint": "#0053db",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-high": "#dce9ff",
        "inverse-primary": "#b4c5ff",
        "secondary": "#565e74",
        "on-tertiary-container": "#ffede6",
        "secondary-container": "#dae2fd",
        "tertiary": "#943700",
        "surface": "#FFFFFF",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-container": "#eeefff",
        "surface-dim": "#cbdbf5",
        "surface-container-low": "#eff4ff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434655",
        "tertiary-container": "#bc4800",
        "inverse-on-surface": "#eaf1ff",
        "text-muted": "#94A3B8",
        "outline-variant": "#c3c6d7",
        "primary-container": "#2563eb",
        "on-secondary-fixed": "#131b2e",
        "on-error": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "text-primary": "#0F172A",
        "on-primary": "#ffffff",
        "background": "#F8FAFC",
        "surface-variant": "#d3e4fe",
        "status-success": "#16A34A",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-bright": "#f8f9ff",
        "border-subtle": "#E2E8F0",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#360f00",
        "on-surface": "#0b1c30",
        "on-secondary-container": "#5c647a",
        "surface-container": "#e5eeff",
        "primary-light": "#EFF6FF",
        "primary": "#004ac6",
        "on-background": "#0b1c30",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary": "#ffffff",
        "primary-hover": "#1D4ED8",
        "status-danger": "#DC2626",
        "text-secondary": "#64748B",
        "outline": "#737686",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb596",
        "inverse-surface": "#213145",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-2xl": "2rem",
        "gutter-desktop": "1.5rem",
        "margin-tablet": "1.25rem",
        "space-md": "0.75rem",
        "space-xl": "1.5rem",
        "margin-desktop": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        margin: "1rem",
        "space-lg": "1rem",
        gutter: "1rem",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-page": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-regular": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-medium": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "display-currency-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "display-currency": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-button": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "caption-medium": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "mono-tabular": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "monospace"],
        "title-card": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-section": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "caption-small": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-page": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-regular": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-medium": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-currency-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-currency": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-button": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "caption-medium": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "mono-tabular": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "title-card": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-section": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "caption-small": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
