import React from "react";
import {
  LayoutDashboard,
  Store,
  Package,
  Receipt,
  BarChart3,
  Settings,
  LogOut,
  LogIn,
  Building2,
  BadgeCheck,
  ShieldCheck,
  Search,
  X,
  Plus,
  PlusCircle,
  Minus,
  Trash2,
  ShoppingCart,
  Banknote,
  Wallet,
  Landmark,
  QrCode,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  HelpCircle,
  TrendingUp,
  ChevronRight,
  ChevronDown,
  ArrowRight,
  Lock,
  User,
  Eye,
  EyeOff,
  Printer,
  Wifi,
  Folder,
  Calculator,
  Calendar,
  FileEdit,
  Save,
  AlertOctagon,
  Coffee,
  Sprout,
  Sparkles,
  Zap,
  Cookie,
  ShoppingBag,
  LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  point_of_sale: Store,
  inventory: Package,
  inventory_2: Package,
  receipt: Receipt,
  receipt_long: Receipt,
  bar_chart: BarChart3,
  settings: Settings,
  logout: LogOut,
  login: LogIn,
  storefront: Store,
  corporate_fare: Building2,
  badge: BadgeCheck,
  admin_panel_settings: ShieldCheck,
  search: Search,
  close: X,
  add: Plus,
  add_circle: PlusCircle,
  add_box: PlusCircle,
  remove: Minus,
  delete: Trash2,
  delete_sweep: Trash2,
  shopping_cart: ShoppingCart,
  shopping_basket: ShoppingCart,
  shopping_bag: ShoppingBag,
  payments: Banknote,
  local_atm: Banknote,
  account_balance_wallet: Wallet,
  account_balance: Landmark,
  qr_code_2: QrCode,
  barcode: QrCode,
  barcode_scanner: QrCode,
  check_circle: CheckCircle2,
  verified: CheckCircle2,
  verified_user: CheckCircle2,
  warning: AlertTriangle,
  priority_high: AlertTriangle,
  error: AlertCircle,
  block: AlertCircle,
  help: HelpCircle,
  trending_up: TrendingUp,
  trending_flat: Minus,
  chevron_right: ChevronRight,
  expand_more: ChevronDown,
  arrow_forward: ArrowRight,
  lock: Lock,
  person: User,
  visibility: Eye,
  visibility_off: EyeOff,
  print: Printer,
  wifi: Wifi,
  category: Folder,
  calculate: Calculator,
  calendar_month: Calendar,
  edit_note: FileEdit,
  save: Save,
  production_quantity_limits: AlertOctagon,
  price_check: TrendingUp,
  query_stats: TrendingUp,
  coffee: Coffee,
  agriculture: Sprout,
  emoji_food_beverage: Coffee,
  clean_hands: Sparkles,
  bolt: Zap,
  cookie: Cookie,
};

interface IconProps {
  name: string;
  className?: string;
  size?: number;
}

export function Icon({ name, className = "w-5 h-5", size }: IconProps) {
  const Component = ICON_MAP[name] || Package;
  return <Component className={className} size={size} />;
}
